import {
  designSystemComponentOverride,
  designSystemConfig,
} from "@repo/eslint-config/design-system"
import { config } from "@repo/eslint-config/react"

/** @type {import("eslint").Linter.Config} */
export default [
  {
    ignores: ["src/components/reui/**"],
  },
  ...config,
  ...designSystemConfig,
  designSystemComponentOverride,
  {
    name: "repo/design-system-chart",
    files: ["src/components/chart.tsx"],
    rules: {
      // Recharts series colors are injected per chart id. Regenerated by ui:sync.
      "shadcn/no-inline-styles": "off",
    },
  },
]
